name = "GlowupVibes"
uuid = "bf6b54a3-cbc8-4fbf-8641-14341a8f5c06"
authors = ["Chelsea Rose Sidrane"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
